module.exports = [
    'Cuando el hombre del saco se va a dormir cada noche, mira en su armario para ver si está Chuck Norris',
    'Si Chuck Norris llega tarde, más le vale al tiempo ir más despacio',
    'Si miras a un espejo y dices Chuck Norris 3 veces, aparecerá y matará a toda tu familia, pero al menos habrás conseguido ver a Chuck Norris',
    'Chuck Norris es el único hombre que ha ganado un partido de tenis contra una pared de ladrillo',
    '¿Qué es lo último que pasa por las mentes de las víctimas de Chuck Norris? Las botas de Chuck Norris',
    'A Chuck Norris le cae bien el Doctor Jaus, por eso sólo lo dejó cojo',
    'Chuck Norris se sabe de memoria todos los decimales del número pi',
    'Cuando Chuck defeca, deja el aire con olor a Axe',
    'Chuck Norris dona sangre a la Cruz Roja frecuentemente, no obstante nunca se trata de su propia sangre',
    'Chuck Norris es capaz de dibujar un mapa completo del metro de Londres meando en la nieve',
    'Chuck Norris es capaz de ganarte a una partida de canicas con piedras cuadradas',
    'Chuck Norris es el único que puede ganar una ruleta rusa llena de balas contra él mismo',
    'El código que escribe Chuck Norris se optimiza solo por miedo a que Chuck Norris decida eliminarlo',
    'Chuck Norris financiaba YouTube, pero se aburrió y decidió venderlo',
    'Chuck Norris ganó el premio nobel de la paz tras algunas amenazas',
    'Chuck Norris ganó una carrera de fórmula uno, empujando el coche con sus propios brazos',
    'Chuck Norris ha estado en Marte, lo cual explica por qué no hay signos de vida',
    'Chuck Norris ha ganado las olimpiadas de Madrid 2012',
    'Chuck Norris desarrolla programas informáticos utilizando el Paint',
    'Chuck Norris inventó la cuchara, porque matar gente con un cuchillo era demasiado fácil',
    'Chuck Norris hizo Roma en un dia',
    'Chuck Norris lanzó una granada y mato a 70 personas, después la granada exploto',
    'Chuck Norris mató a su sombra, nadie sigue a Chuck Norris',
    'Chuck Norris muele el cafe con sus dientes y calienta el agua con su propia rabia',
    'Chuck Norris no cree en Dios, Dios cree en Chuck Norris',
    'Chuck Norris no levanta la tapa al orinar, la tapa se levanta sola cuando Chuck entra en el cuarto de baño. De hecho, generalmente la tapa sale corriendo',
    'Chuck Norris no se afeita. se patea la cara. la unica cosa que puede cortar a Chuck Norris es Chuck Norris',
    'Chuck Norris no tiene horno ni microondas, porque la venganza es un plato que se sirve frio',
    'Chuck Norris pidió un Big Mac en el Burger King. Y le dieron uno',
    'Chuck Norris pudo inflar las ruedas de su coche tan solo con la fuerza de sus pulmones. Por cierto, los neumáticos estaban pinchados',
    'Chuck Norris puede comer sopa con un tenedor',
    'Chuck Norris puede cerrar de un golpe una puerta giratoria',
    'Chuck Norris tiene el corazón de un niño, en un bote de cristal en su escritorio',
    'La raíz cuadrada de Chuck Norris es dolor',
    'Chuck Norris no duerme, espera',
    'Chuck Norris ha demandado a la ene be ce, alegando que Ley y Orden son marcas registradas para su pierna derecha e izquierda',
    'Chuck Norris sopló las velas de cumpleaños en Madrid hace algún tiempo. Ese día se registraron los primeros incidentes por la borrasca Filomena',
    'Se sabe con certeza que las lágrimas de Chuck Norris curan el cáncer. No obstante, nadie lo ha visto llorar aún',
    'Si puedes ver a Chuck Norris, él puede verte. Si no puedes ver a Chuck Norris, puede que estes a sólo unos segundos de tu muerte',
    'Chuck Norris es el único que ha contado hasta el infinito, y lo ha hecho dos veces',
    '¿Sabes por qué Chuck Norris no tiene corazón? Porque decidio prescindir de él después de tener dos infartos en 2018'
]