module.exports = [
    'Chuck Norris tiene el corazon de un ninio. En un bote de cristal en su escritorio',
    'La raiz cuadrada de Chuck Norris es dolor',
    'Chuck Norris no duerme. Espera',
    'Chuck Norris ha demandado a la ene be ce. alegando que Ley y Orden son marcas registradas para su pierna derecha e izquierda',
    'Chuck Norris soplo una vez las velas de cumpleanios. Hubo Eclipse.',
    'Las lagrimas de Chuck Norris curan el cancer. Es una pena que el no haya llorado nunca.',
    'Si puedes ver a Chuck Norris. el puede verte. Si no puedes ver a Chuck Norris. puede que estes a solo unos segundos de tu muerte',
    'Chuck Norris ha contado hasta el infinito. dos veces',
    'Sabes por que Chuck Norris no tiene corazon? Porque decidio prescindir de el despues de tener dos infartos en 2018',
    'Cuando el Hombre del Saco se va a dormir cada noche. mira en su armario para ver si esta Chuck Norris',
    'Si Chuck Norris llega tarde. mas le vale al tiempo ir mas despacio',
    'Si miras a un espejo y dices Chuck Norris 3 veces. aparecera y matara a toda tu familia. pero al menos habras conseguido ver a Chuck Norris',
    'Chuck Norris es el unico hombre que ha ganado un partido de tenis contra una pared de ladrillo',
    'Que es lo ultimo que pasa por las mentes de las victimas de Chuck Norris? Las botas de Chuck Norris',
    'A Chuck Norris le cae bien el Doctor Jaus. por eso solo lo dejo cojo',
    'Chuck Norris conoce todo los decimales del numero pi',
    'Cuando Chuck defeca deja el aire con olor a Axe',
    'Chuck Norris dona sangre a la Cruz Roja frecuentemente. Lamentablemente nunca es la suya',
    'Chuck Norris es capaz de dibujar un mapa completo del metro de Londres meando en la nieve',
    'Chuck Norris es capaz de ganarte a una partida a las canicas con piedras cuadradas',
    'Chuck Norris es el unico que puede ganar una ruleta rusa llena de balas contra el mismo',
    'Chuck Norris escribe codigo que se optimiza solo',
    'Chuck Norris financiaba YouTube. pero se aburrio y decidio venderlo a gugel',
    'Chuck Norris gano el premio nobel de la paz tras algunas amenazas.',
    'Chuck Norris gano una carrera de formula uno. empujando el coche con sus propios brazos.',
    'Chuck Norris ha estado en Marte. lo que explica por que no hay signos de vida.',
    'Chuck Norris ha ganado las olimpiadas de Madrid 2012.',
    'Chuck Norris hace programas utilizando el Paint.',
    'Chuck Norris invento la cuchara. porque matar gente con un cuchillo era demasiado facil',
    'Chuck Norris hizo Roma en un dia.',
    'Chuck Norris lanzo una granada y mato a 70 personas. Despues la granada exploto.',
    'Chuck Norris mato a su sombra. Nadie sigue a Chuck Norris.',
    'Chuck Norris muele el cafe con sus dientes y calienta el agua con su propia rabia.',
    'Chuck Norris no cree en Dios. Dios cree en Chuck Norris',
    'Chuck Norris no levanta la tapa al orinar. La tapa se levanta sola al entrar en el cuarto de banio. De hecho. generalmente la tapa sale corriendo.',
    'Chuck Norris no se afeita. se patea la cara. la unica cosa que puede cortar a Chuck Norris es Chuck Norris',
    'Chuck Norris no tiene horno ni microondas. porque la venganza es un plato que se sirve frio.',
    'Chuck Norris pidio un Big Mac en el Burger King. Y le dieron uno.',
    'Chuck Norris pudo inflar las ruedas de su coche tan solo con la fuerza de sus pulmones. Por cierto. Los neumaticos estaban pinchados.',
    'Chuck Norris puede comer sopa con un tenedor.',
    'Chuck Norris puede cerrar de un golpe una puerta giratoria.'
]